GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/1

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Rabeux",
    "firstname": "Florian"
}

###

PUT http://localhost:3000/api/users/19ea3b58-31d7-464b-b516-8d8126194957
Content-Type: application/json

{
    "id": "19ea3b58-31d7-464b-b516-8d8126194957",
    "name": "Rabeux2",
    "firstname": "Florian"
}

###

DELETE http://localhost:3000/api/users/2
